name: GitHub profile

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    name: Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #- uses: lowlighter/metrics@master
      #  name: Generate metrics
      #  with:
      #    filename: assets/metrics/classic.svg
      #    token: ${{ secrets.METRICS_TOKEN }}
      #    base: header, repositories
      #    plugin_lines: yes
      #    plugins_errors_fatal: yes
      - uses: lowlighter/metrics@master
        name: Generate achievements
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics/achievements.svg
          base: ""
          plugin_achievements: yes
          plugins_errors_fatal: yes
      - uses: lowlighter/metrics@master
        name: Generate languages stats
        with:
          filename: assets/metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, twig, scss, yaml, json, markdown, vim, viml, vimscript, vim-script
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 15
